# Generated by Django 5.2.7 on 2026-05-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cart",
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(
                fields=["customer_id"], name="restaurants_custome_63a38c_idx"
            ),
        ),
    ]
