# Generated by Django 5.2.7 on 2026-05-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0002_alter_cart_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="restauranttiming",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="pin_code",
            field=models.CharField(max_length=6),
        ),
        migrations.AddIndex(
            model_name="restaurant",
            index=models.Index(
                fields=["is_deleted", "pin_code", "name"],
                name="restaurants_is_dele_9d99d9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="restaurant",
            index=models.Index(
                fields=["is_deleted", "cuisine_type", "name"],
                name="restaurants_is_dele_dfd570_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="menuitem",
            constraint=models.UniqueConstraint(
                fields=("restaurant", "name"), name="unique_menu_item_per_restaurant"
            ),
        ),
        migrations.AddConstraint(
            model_name="restauranttiming",
            constraint=models.UniqueConstraint(
                fields=("restaurant", "day_of_week"),
                name="unique_restaurant_day_of_week",
            ),
        ),
    ]
