# Generated by Django 5.2.7 on 2026-05-14 08:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0003_alter_restauranttiming_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="restaurantreview",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="restaurantreview",
            name="update_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="id",
            field=models.CharField(
                default=uuid.UUID("a549926c-43db-43be-8863-76afec8744cc"),
                editable=False,
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="restaurantreview",
            constraint=models.UniqueConstraint(
                fields=("restaurant", "customer_id"), name="unique_restaurant_review"
            ),
        ),
        migrations.RemoveField(
            model_name="restaurantreview",
            name="item_id",
        ),
    ]
