# Generated by Django 5.2.7 on 2026-04-22 12:33

import utils.uuid_util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                default=utils.uuid_util.generate_uuid,
                editable=False,
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="address",
            unique_together={("user", "label")},
        ),
    ]
