# Generated by Django 5.2.7 on 2026-05-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
