# Generated by Django 5.2.7 on 2026-05-13 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="pin_code",
        ),
        migrations.AddField(
            model_name="address",
            name="pincode",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid phone number.",
                        regex="^\\+?[1-9]\\d{9,14}$",
                    )
                ],
            ),
        ),
    ]
