# Generated by Django 5.2.7 on 2026-05-14 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_address_pin_code_address_pincode_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="address",
            unique_together={("user", "label", "pincode")},
        ),
    ]
