# Generated by Django 5.2.7 on 2026-04-16 16:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cuisine_type', models.CharField(choices=[('SOUTH_INDIAN', 'South_indian'), ('NORTH_INDIAN', 'North_indian'), ('CHINESE', 'Chinese'), ('ITALIAN', 'Italian'), ('FAST_FOOD', 'Fast_food'), ('BAKERY', 'Bakery'), ('CAFE', 'Cafe')], max_length=255)),
                ('address', models.TextField()),
                ('pin_code', models.CharField(max_length=10)),
                ('is_veg_only', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='restaurant__name_cf5999_idx'), models.Index(fields=['owner'], name='restaurant__owner_i_a0af92_idx')],
            },
        ),
    ]
