# Generated by Django 5.2.7 on 2026-04-18 07:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cuisine_type', models.CharField(choices=[('SOUTH_INDIAN', 'South_indian'), ('NORTH_INDIAN', 'North_indian'), ('CHINESE', 'Chinese'), ('ITALIAN', 'Italian'), ('FAST_FOOD', 'Fast_food'), ('BAKERY', 'Bakery'), ('CAFE', 'Cafe')], max_length=255)),
                ('address', models.TextField()),
                ('pin_code', models.CharField(max_length=10)),
                ('is_veg_only', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('STARTER', 'Starter'), ('MAIN_COURSE', 'Main_course'), ('BREADS', 'Breads'), ('RICE_AND_BIRYANI', 'Rice_and_biryani'), ('BEVERAGES', 'Beverages'), ('DESSERTS', 'Desserts'), ('SOUPS', 'Soups'), ('SALADS', 'Salads'), ('COMBO', 'Combo')], max_length=30)),
                ('is_veg', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('preparation_time_in_minutes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restaurant.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_code', models.CharField(max_length=6)),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_delivery_mins', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['name'], name='restaurant__name_cf5999_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['owner'], name='restaurant__owner_i_a0af92_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['restaurant'], name='restaurant__restaur_4cd8f2_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryzone',
            index=models.Index(fields=['restaurant'], name='restaurant__restaur_8ed95b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deliveryzone',
            unique_together={('restaurant', 'pin_code')},
        ),
        migrations.AlterUniqueTogether(
            name='restaurantreview',
            unique_together={('restaurant', 'customer')},
        ),
        migrations.AlterUniqueTogether(
            name='restauranttiming',
            unique_together={('restaurant', 'day_of_week')},
        ),
    ]
