# Generated by Django 4.2.7 on 2026-04-20 05:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.CharField(
                        default="a8400e7c-f7bb-4098-9531-866dbb868beb",
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("customer_id", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DeliveryZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pin_code", models.CharField(max_length=6)),
                (
                    "delivery_fee",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "estimated_delivery_mins",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.CharField(
                        default="fcd7c4d9-e759-4522-a89f-c40da0b6a009",
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("STARTER", "Starter"),
                            ("MAIN_COURSE", "Main_course"),
                            ("BREADS", "Breads"),
                            ("RICE_AND_BIRYANI", "Rice_and_biryani"),
                            ("BEVERAGES", "Beverages"),
                            ("DESSERTS", "Desserts"),
                            ("SOUPS", "Soups"),
                            ("SALADS", "Salads"),
                            ("COMBO", "Combo"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_veg", models.BooleanField(default=False)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "preparation_time_in_minutes",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.CharField(
                        default="f5f5f6ae-d69b-4bb7-8df2-ea2aab3bda6c",
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("owner_id", models.CharField(max_length=255)),
                (
                    "cuisine_type",
                    models.CharField(
                        choices=[
                            ("SOUTH_INDIAN", "South_indian"),
                            ("NORTH_INDIAN", "North_indian"),
                            ("CHINESE", "Chinese"),
                            ("ITALIAN", "Italian"),
                            ("FAST_FOOD", "Fast_food"),
                            ("BAKERY", "Bakery"),
                            ("CAFE", "Cafe"),
                        ],
                        max_length=255,
                    ),
                ),
                ("address", models.TextField()),
                ("pin_code", models.CharField(max_length=10)),
                ("is_veg_only", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="RestaurantTiming",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (1, "Monday"),
                            (2, "Tuesday"),
                            (3, "Wednesday"),
                            (4, "Thursday"),
                            (5, "Friday"),
                            (6, "Saturday"),
                            (7, "Sunday"),
                        ]
                    ),
                ),
                ("open_time", models.TimeField()),
                ("close_time", models.TimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurant.restaurant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RestaurantReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_id", models.CharField(max_length=255, unique=True)),
                ("customer_id", models.CharField(max_length=255)),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("review_text", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restaurant_reviews",
                        to="restaurant.restaurant",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="restaurant",
            index=models.Index(
                fields=["is_deleted", "cuisine_type"],
                name="restaurant__is_dele_0fd038_idx",
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu_items",
                to="restaurant.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="deliveryzone",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="restaurant.restaurant"
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="restaurant.cart"
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="menu_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="restaurant.menuitem"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cart",
            unique_together={("id", "customer_id")},
        ),
        migrations.AlterUniqueTogether(
            name="restauranttiming",
            unique_together={("restaurant", "day_of_week")},
        ),
        migrations.AlterUniqueTogether(
            name="restaurantreview",
            unique_together={("restaurant", "customer_id")},
        ),
        migrations.AddIndex(
            model_name="deliveryzone",
            index=models.Index(
                fields=["restaurant"], name="restaurant__restaur_8ed95b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="deliveryzone",
            unique_together={("restaurant", "pin_code")},
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "menu_item")},
        ),
    ]
