# Generated by Django 5.2.7 on 2026-04-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="deliveryzone",
            name="restaurant__restaur_8ed95b_idx",
        ),
        migrations.AddField(
            model_name="cartitem",
            name="item_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="cart",
            name="id",
            field=models.CharField(
                default="313dfe8c-f8ee-4688-a8f7-64a6dda20f7e",
                editable=False,
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="id",
            field=models.CharField(
                default="faa11150-ce2b-4bf0-80ea-4c5062c30282",
                editable=False,
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="id",
            field=models.CharField(
                default="895eafba-161b-4912-a6b6-266cd51361f4",
                editable=False,
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
