# Generated by Django 5.2.7 on 2026-04-17 12:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("STARTER", "Starter"),
                            ("MAIN_COURSE", "Main_course"),
                            ("BREADS", "Breads"),
                            ("RICE_AND_BIRYANI", "Rice_and_biryani"),
                            ("BEVERAGES", "Beverages"),
                            ("DESSERTS", "Desserts"),
                            ("SOUPS", "Soups"),
                            ("SALADS", "Salads"),
                            ("COMBO", "Combo"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_veg", models.BooleanField(default=False)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "preparation_time_in_minutes",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_items",
                        to="restaurant.restaurant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["restaurant"], name="restaurant__restaur_4cd8f2_idx"
                    )
                ],
            },
        ),
    ]
