# Generated by Django 5.2.7 on 2026-04-22 12:33

import utils.uuid_util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "restaurant",
            "0002_remove_deliveryzone_restaurant__restaur_8ed95b_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="id",
            field=models.CharField(
                default=utils.uuid_util.generate_uuid,
                editable=False,
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="id",
            field=models.CharField(
                default=utils.uuid_util.generate_uuid,
                editable=False,
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="id",
            field=models.CharField(
                default=utils.uuid_util.generate_uuid,
                editable=False,
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="restaurantreview",
            name="item_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
