# Generated by Django 5.2.7 on 2026-05-05 07:05

import orders.constants.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_orderitem_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="scheduled_for",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("SCHEDULED", "Scheduled"),
                    ("PLACED", "Placed"),
                    ("CONFIRMED", "Confirmed"),
                    ("PREPARING", "Preparing"),
                    ("OUT_OF_DELIVERY", "Out_of_delivery"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                ],
                default=orders.constants.enums.OrderStatus["PLACED"],
                max_length=255,
            ),
        ),
    ]
