# Generated by Django 5.2.7 on 2026-05-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_scheduled_for_alter_order_status"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="order",
            name="orders_orde_restaur_79a0fa_idx",
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="orders_orde_custome_59b6fb_idx",
        ),
        migrations.AlterField(
            model_name="order",
            name="address_id",
            field=models.IntegerField(),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["restaurant_id", "-created_at"],
                name="orders_orde_restaur_7d58ee_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["customer_id", "-created_at"],
                name="orders_orde_custome_413d7d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["promo_code"], name="orders_orde_promo_c_96f65d_idx"
            ),
        ),
    ]
