# Generated by Django 5.2.7 on 2026-04-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_order_orderitem_order_order_order_restaur_df5d4f_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.CharField(
                default="b05204a4-3f16-4202-86fe-131890c54819",
                max_length=255,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
