# Generated by Django 5.2.7 on 2026-04-22 12:33

import utils.uuid_util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_alter_order_promo_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.CharField(
                default=utils.uuid_util.generate_uuid,
                max_length=255,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
